// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.MicrographCache.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FeedHoursHistory
    {
        /// <summary>
        /// Initializes a new instance of the FeedHoursHistory class.
        /// </summary>
        public FeedHoursHistory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FeedHoursHistory class.
        /// </summary>
        public FeedHoursHistory(IList<double?> changes = default(IList<double?>))
        {
            Changes = changes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Changes")]
        public IList<double?> Changes { get; set; }

    }
}
