// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.MicrographCache.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.MicrographCache;
    using Lykke.Service.MicrographCache.Client;
    using Lykke.Service.MicrographCache.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FeedHoursHistory
    {
        /// <summary>
        /// Initializes a new instance of the FeedHoursHistory class.
        /// </summary>
        public FeedHoursHistory()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FeedHoursHistory class.
        /// </summary>
        public FeedHoursHistory(string assetPairId = default(string), IList<double?> changes = default(IList<double?>))
        {
            AssetPairId = assetPairId;
            Changes = changes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Changes")]
        public IList<double?> Changes { get; set; }

    }
}
